application: slack-assistant-yui
version: 0-00-001
runtime: go
api_version: go1
threadsafe: yes

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

skip_files:
- ^temp
- \.gitignore
- ^\.git/.*
- ^LICENSE\.txt$
- ^.*start$
- \.vscode
- \.envrc

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /.*
  script: _go_app